### ISSUE TITLE
Can't select which account to authorize when logged into multiple Basecamp accounts

### ISSUE THREAD

**Issue by trackedsupport** [basecamp/bc3-api#269] opened 2020-05-06 16:28 UTC
I've seen issues where users have a legacy Basecamp account and a Basecamp 3 account and when they try to authorize Tracked to access their account, it sometimes uses their Basecamp legacy account and not their Basecamp 3 account. 

My current solution is to have them log out of all Basecamp accounts and then log back in with the Basecamp 3 account, authorize, and then they can log back into their legacy account. 

**Page:** https://launchpad.37signals.com/authorization/new

One thing I noticed is that their authorization screen does not show Basecamp 3. i.e. 
![image (1)](https://user-images.githubusercontent.com/29817223/81202706-f9f90600-8f94-11ea-81fe-12cb98c98385.png)

**Comment by rosa** [comment] 2020-05-06 19:30
Thanks for reporting this, @trackedsupport, we'll take a look and let you know.

**Comment by trackedsupport** [comment] 2020-06-19 21:32
This happened for two different customers today. Let me know if there is anything I can do.

**Comment by rosa** [comment] 2020-06-21 11:10
Hey @trackedsupport, so sorry for the delay looking into this. I finally took a look (we've been quite swamped with other stuff) and I couldn't reproduce the issue. We correctly show the different accounts the user would need to authorize:

<img width="644" alt="Screenshot 2020-06-21 at 13 06 58" src="https://user-images.githubusercontent.com/813033/85223052-24c1e100-b3c0-11ea-841c-a431509388ba.png">

I think I misunderstood your first description of the problem. I thought we were failing to show the accounts the user had access to, but now I'm seeing that in your case, users have access to different identities, identified by different credentials. In this case the behaviour you're seeing is completely expected. These identities are independent and we can't show them together, they're unrelated. 

My advice for these customers is to get in touch [with our support team](https://basecamp.com/support) and ask to have these identities merged, so that they can manage all their Basecamp accounts under the same identity. 

Finally, about not showing "Basecamp 3" in that dialog with only one app, that's expected as well. We do show Basecamp 3's logo, but we don't show the product name because there's just one account, we don't need to distinguish it from others like in my screenshot.

**Closed by rosa** 2020-06-21 11:10 UTC

**Comment by trackedsupport** [comment] 2020-06-21 11:19
Yea sorry I meant Basecamp user identities.  They have two different user identities with two different email addresses so when they go to that integrate screen they can’t choose which user identity nor do they know which user identity it’s using. 

So someone is using user identity B but then they go to the integrate screen it seems to choose user identity A. That’s why I tell them to log out both Basecamp users, then log in with user B, authorize Tracked, then log back in with user A.

**Comment by rosa** [comment] 2020-06-21 11:41
Yes, that makes perfect sense. If they get in touch with support, they can get these two, A and B, merged together so they can access both accounts under the same credentials. Otherwise, I'm afraid they'd need to continue signing out and in into the right account to authorize the right one.
