### ISSUE TITLE
Problem with bots using let's encrypt cert

### ISSUE THREAD

**Issue by victor-teles** [basecamp/bc3-api#314] opened 2021-10-01 14:39 UTC
Hi,

I'm having some problems accessing my bots because the root certificate of lets encrypt has expired!

https://borncity.com/win/2021/09/30/sept-30-2021-will-we-see-trouble-with-old-lets-encrypt-certificates/
https://letsencrypt.org/docs/certificate-compatibility/

![image](https://user-images.githubusercontent.com/78874691/135638679-4402c5f4-8536-4044-9f29-744982d71370.png)

**Comment by rosa** [comment] 2021-10-01 14:57
Hey @victor-teles! You'll need to renew these certs. These chatbots aren't maintained by us, we only maintain the API, and the error happens when we try to call the URL configured, because of the expired certificate.

**Comment by rosa** [comment] 2021-10-01 15:14
Apologies, @victor-teles, I misread, I didn't realise you mentioned _the root_ certificate of Let's Encrypt, I thought you were referring to your own Let's Encrypt certificates. I'll look into this.

**Comment by mwbrooks** [comment] 2021-10-01 16:52
@rosa 👋🏻 it looks like we're seeing a similar root certificate error with webhook deliveries:

```
GET /buckets/1/webhooks/3.json
```

```
"recent_deliveries": [
    {
        ...
        "response": {
            "error": "#<RestClient::SSLCertificateNotVerified: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)>"
        }
    }
]
```

Hope that helps you track this down 🙂

**Comment by rosa** [comment] 2021-10-01 17:07
Oh, hey @mwbrooks! Indeed! Same root cause. Thank you so much for letting us know. Our Ops team already figured out the problem and are working on fixing it right now via a workaround they found ([removing the old expired cert](https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/) from our servers), as we already had the right one, ISRG’s “ISRG Root X1”, but another issue prevented BC3 from using it for webhook and chatbot calls. 

I'll update when it's fixed!

**Comment by rosa** [comment] 2021-10-01 17:55
Ok, this should be good now! Could you try again to see if things look fine on your side?

**Comment by mwbrooks** [comment] 2021-10-01 18:43
@rosa thanks a bunch! We're seeing activity coming through the webhooks successfully 🎉

**Comment by mwbrooks** [comment] 2021-10-01 18:50
@rosa I'm going to look into whether any existing webhook's that triggered during the outage were deactivated. Right now, we're seeing a lot of old activity coming through, so it appears that the webhook triggers were queued up.

Off the top of your head, so you know whether webhook's with activity during the outage would be deactivated? I know Basecamp's API will attempt 10 deliveries before deactiving the webhook, but I'm unsure if that policy was enforced with this error:

 > Basecamp will attempt to call the payload URL up to 10 times before deactivating the webhook. The duration between attempts will grow exponentially longer to give your service time to recover. Basecamp will only consider a HTTP status code in the 2xx range to be a successful response. We will not follow a 3xx redirect.

**Comment by rosa** [comment] 2021-10-02 09:17
> Off the top of your head, do you know whether webhooks with activity during the outage would be deactivated? I know Basecamp's API will attempt 10 deliveries before deactivating the webhook, but I'm unsure if that policy was enforced with this error

Yes, they should have been deactivated if we got to 10 failed attempts with this error, unfortunately. The exponential backoff lasts for about 2 hours, so any webhook deliveries queued within 2 hours before our resolution would have been retried (as you saw) as they would still be within the 10 retries, and these webhooks wouldn't have been deactivated. However, any webhooks that triggered before 2 hours before resolution would have been deactivated, unfortunately 😞 

I can help with this, though. If you let me know your account, I can find webhooks deactivated in the last 36 hours and make sure they're activated again, so you don't have to go one by one. 

So sorry about this!

**Comment by mwbrooks** [comment] 2021-10-04 05:14
Hey @rosa, thanks for the clarification and sorry about the slow response. 

Based on the 2 hour window, I think you're right that some webhooks would have been deactivated. The good news is that we have a "health check" worker process that audits everyone's webhooks every 12 hours. It looks like it was able to reactivate the customers who were affected, so we should be okay!

Thanks for offering to find the webhooks that were deactivated. It feels really good knowing that the Basecamp API has you behind it!

_(I think it's safe to close this issue when you have the time)_

Cheers,
Michael

**Comment by rosa** [comment] 2021-10-04 06:49
> The good news is that we have a "health check" worker process that audits everyone's webhooks every 12 hours.

Wow! Well done! 👏 👏 

Thank you so much for your help and understanding!

**Closed by rosa** 2021-10-04 06:49 UTC
