### ISSUE TITLE
Webhook problem

### ISSUE THREAD

**Issue by jvmasera** [basecamp/bc3-api#265] opened 2020-03-16 19:17 UTC
My notifications webhooks are being automatically disabled with the following error:
![3Cscreencapture-1584367408626](https://user-images.githubusercontent.com/15824982/76792336-9a0a8e00-67a1-11ea-9f84-dd89f38a28f9.png). How can I be solving this?

**Comment by rosa** [comment] 2020-03-16 19:43
Hi @jvmasera! Looks like the app that is behind the callback URL you configured for your webhook is taking too long to respond (over 10 seconds). To solve this, you should ensure that whatever action you're taking when you receive our request doesn't take over 10 seconds.

I hope this helps!

**Comment by jvmasera** [comment] 2020-03-16 19:50
@rosa, strange, because only in this specific project that is returning this error to me. The code is the same for all projects.

**Comment by JBNavadiya** [comment] 2020-03-24 07:20
@rosa we're also facing a similar issues. I don't think the problem is with the time out. I have checked in 15  - 20 projects/teams (we have more than that actually ~ 100) and found that webhook is still configured with the endpoint but it is getting disabled without any error/timeout thing. There is no pattern in date or calls or events. I think there is an issue from the BC3 API. This is causing us on critical level on business. We are highly relying on this. Request you guys to help us.
P.s We have already raised the support yesterday. I dont have the ticket id as it is not mentioned in support@basecamp.com email response.

**Comment by rosa** [comment] 2020-03-24 09:03
> found that webhook is still configured with the endpoint but it is getting disabled without any error/timeout thing

Hi @JBNavadiya, have you checked the last five deliveries and responses?

**Comment by rosa** [comment] 2020-03-24 09:04
> strange, because only in this specific project that is returning this error to me. The code is the same for all projects.

It can be the same code but still take different time to run depending on the request we send. Have you checked your app logs to verify that you're indeed responding in less than 10 seconds to the specific webhook requests that failed?

**Comment by JBNavadiya** [comment] 2020-04-11 04:16
Thanks, @rosa. I think it got resolved as of now. What we have observed is that if webhook call didn't get any kind of response/return value (i.e success) from the server then webhook gets automatically disabled after some time. You can confirm the same or you can try to replicate this case from your end as well.

**Comment by rosa** [comment] 2020-04-11 09:37
> What we have observed is that if webhook call didn't get any kind of response/return value (i.e success) from the server

Ah, yes, that makes perfect sense. We're probably disabling due a timeout, waiting for a response that never comes.

**Closed** 2020-05-06 19:32 UTC
