### ISSUE TITLE
Webhook: Answer to Question Recording does not include creator

### ISSUE THREAD

**Issue by wm** [basecamp/bc3-api#68] opened 2016-10-15 19:53 UTC
The documentation suggests that the recording object should have a creator element. However when I get recordings sent to my API it is missing that nested object.

REQUEST:

```
{
  "id": xxxxxxx,
  "kind": "question_answer_created",
  "details": {
    "notified_recipient_ids": []
  },
  "created_at": "2016-10-15T15:40:19.362-04:00",
  "recording": {
    "id": xxxxxxx,
    "status": "active",
    "created_at": "2016-10-15T15:40:19.340-04:00",
    "updated_at": "2016-10-15T15:40:19.347-04:00",
    "type": "Question::Answer",
    "url": "https://3.basecampapi.com/xxxxxxx/buckets/xxxxxxx/question_answers/xxxxxxx.json",
    "app_url": "https://3.basecamp.com/xxxxxxx/buckets/xxxxxxx/questions/258854860/answers/2016-10-15#__recording_xxxxxxx",
    "parent": {
      "id": xxxxxxx,
      "title": "What did you do yesterday, what are you doing today, and are there blockers?",
      "type": "Question",
      "url": "https://3.basecampapi.com/xxxxxxx/buckets/xxxxxxx/questions/xxxxxxx.json",
      "app_url": "https://3.basecamp.com/xxxxxxx/buckets/xxxxxxx/questions/xxxxxxx"
    },
    "bucket": {
      "id": xxxxxxx,
      "name": "Integration Test",
      "type": "Project"
    },
    "title": "Answer to “What did you do yesterday, what are you doing today, and are there blockers?”",
    "content": "<div><strong>Yesterday:</strong></div><ul><li>some answer</li><li>some other answer</li></ul><div><strong>Today:</strong></div><ul><li>an answer</li><li>another answer</li></ul><div><br></div>"
  }
}
```

It would be really useful if I could get creator nested in the recording per the documentation

```
"creator": {
      "id": 1007299165,
      "attachable_sgid": "BAh7CEkiCGdpZAY6BkVUSSIrZ2lkOi8vYmMzL1BlcnNvbi8xMDA3Mjk5MTY1P2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--c28a27d0c490353fc1a5c2a50ce8eda0fae07370",
      "name": "Matt Donahue",
      "email_address": "matt@honchodesign.com",
      "personable_type": "User",
      "title": "Global Data Strategist",
      "bio": null,
      "created_at": "2016-07-19T21:27:47.654Z",
      "updated_at": "2016-07-19T21:27:47.654Z",
      "admin": false,
      "owner": false,
      "time_zone": "America/Chicago",
      "avatar_url": "https://3.basecamp-static.com/195539477/people/BAhpBF0qCjw=--21513efb0cf6f64f7a0720b2c56ac6145ae6680c/avatar-64-x4"
    },
```

**Comment by georgeclaghorn** [comment] 2016-10-15 23:24
Hey @wm, could you send an email to support@basecamp.com with the `id` of a `question_answer_created` event that did not include the recording's creator?

**Comment by SeBsZ** [comment] 2017-02-27 16:05
Is this still an issue or am I doing something wrong?

I tried several webhooks including `message_created` and `todo_created` and none contain the recording's creator.

630231172 and 630195179 are two example event ids that did not include a creator. Could you tell me what the problem is here? It would be really nice if the creator was included in the webhook payload.

**Comment by archon810** [comment] 2017-03-06 09:00
@georgeclaghorn Any idea when this will be fixed? It's a blocker for us and we can't migrate to BC3 from BC2 until it's resolved.

Thanks.

**Comment by SeBsZ** [comment] 2017-03-06 09:03
A more recent ID if you need it for investigating this problem @georgeclaghorn is 643402810 . Thanks in advance!

**Comment by georgeclaghorn** [comment] 2017-03-06 19:53
Sorry for the delay, all! I just deployed a fix and confirmed that recording creator data is included in webhook payloads now.

**Comment by archon810** [comment] 2017-03-06 19:54
👏

**Closed by georgeclaghorn** 2017-03-06 19:53 UTC
