### ISSUE TITLE
Account based webhooks

### ISSUE THREAD

**Issue by raulpopadineti** [basecamp/bc3-api#121] opened 2017-05-03 12:36 UTC
Currently there's no way to subscribe to project events (create/update/delete). 

When a client creates a new project, we'd have to fetch on a regular interval all projects and see if a new one is created. Instead it would be easier if there'd be an account based webhook that triggers on project create/update/delete.

**Comment by raulpopadineti** [comment] 2017-05-31 12:09
ping.

**Comment by danielhaan** [comment] 2018-02-06 16:29
I'm also interested in this

**Comment by raulpopadineti** [comment] 2018-02-27 12:42
@javan ping.

**Comment by raulpopadineti** [comment] 2018-09-25 09:38
Any update on this?

**Comment by rosa** [comment] 2018-09-25 10:03
Hey @raulpopadineti, I'm afraid not. We haven't decided yet whether we'll implement this feature. It's not trivial at all to add given how our webhooks work right now, and we'd need to budget time for it as our team is very small. Right now we don't have any plans to do it, which doesn't mean it will never happen, but it means it won't happen in the near future.

**Comment by rosa** [comment] 2019-01-09 15:17
Closing this, since we don't have any plans to implement this in the near future. Sorry about that!

**Closed by rosa** 2019-01-09 15:17 UTC
Labels: enhancement, webhooks

**Comment by raulpopadineti** [comment] 2019-01-09 15:45
@rosa mkay...I wasn't expecting this. When you say `in the near future` I guess that means not in 2019, right? Last time we discussed was at the end of Sep and it took 3 months to decide whether to implement it or not.

This isn't helping integrators automate their Basecamp integrations, especially since people don't want to waste time linking new projects everyday (e.g.: a customer support team that manages their clients in Basecamp and creates a new project every day for each business client). 

I guess the `update` event will put a lot of load on your servers, but the create/archive/delete, shouldn't. Could you at least consider this for the latter? It shouldn't be hard to implement either as there are not that many places from which you can add, archive or delete a project in Basecamp.

**Comment by rosa** [comment] 2019-01-09 16:01
Hey @raulpopadineti, I understand this doesn't help and I'm sorry! The problem is not really the load from the new kind of events, it's the way our webhooks work. They are linked always to a project, so having account level webhooks is a significant project that would take some time. We've decided not to allocate time to work on that feature. We've also written more about [what to expect from this API](https://github.com/basecamp/api#realistic-expectations) so decisions like this one don't come as a surprise.

**Comment by raulpopadineti** [comment] 2019-12-12 12:15
Any way of reconsidering this after one more year? 😄

**Comment by rosa** [comment] 2019-12-12 12:44
I'm sorry @raulpopadineti! Still the same as a year ago 😞 That is, no plans to implement this in the future. I'm very sorry!

**Comment by raulpopadineti** [comment] 2019-12-12 13:35
Gotcha! Thanks for the quick reply.
